// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Web.Mega.Finance.Models
{
    public partial class ms_storage_location
    {
        public ms_storage_location()
        {
            tr_bpkb = new HashSet<tr_bpkb>();
        }

        [Key]
        public int location_id { get; set; }
        [StringLength(100)]
        [Unicode(false)]
        public string location_name { get; set; }

        [InverseProperty("location")]
        public virtual ICollection<tr_bpkb> tr_bpkb { get; set; }
    }
}