// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Web.Mega.Finance.Api.Models
{
    public partial class MegaFinanceContext : DbContext
    {
        public MegaFinanceContext()
        {
        }

        public MegaFinanceContext(DbContextOptions<MegaFinanceContext> options)
            : base(options)
        {
        }

        public virtual DbSet<ms_storage_location> ms_storage_location { get; set; }
        public virtual DbSet<ms_user> ms_user { get; set; }
        public virtual DbSet<tr_bpkb> tr_bpkb { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<ms_storage_location>(entity =>
            {
                entity.HasKey(e => e.location_id)
                    .HasName("PK__ms_stora__771831EA93B09DCF");
            });

            modelBuilder.Entity<ms_user>(entity =>
            {
                entity.HasKey(e => e.user_id)
                    .HasName("PK__ms_user__B9BE370F411FBAEB");
            });

            modelBuilder.Entity<tr_bpkb>(entity =>
            {
                entity.HasOne(d => d.location)
                    .WithMany(p => p.tr_bpkb)
                    .HasForeignKey(d => d.location_id)
                    .HasConstraintName("FK__tr_bpkb__locatio__3B75D760");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}